### ISSUE TITLE
Swapping without helmet deletes all armor

### ISSUE THREAD

**Issue by thomaswilliams123** [taggernation/ArmorSwap#4]
Hi, I was testing out your pluggin for my server and when I swapped my diamond armor with a helmet missing, it deleted my whole armor. I tested this with a few different items missing and when an item is missing, it will delete the armor below it (like below on the person) when placed on a stand or taking it off of a stand.

For the time being, I will only swap with a full armor equiped, but just wanted to bring attention to this incase it wasn't known

**Comment by toonystank** [comment]
Fixed
